// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBpnuJIWW8Sp6H7yNBiQnWiMwWk-l61Oik',
//     appId: '1:683953220299:web:98e610cea94f5cf88d894e',
//     messagingSenderId: '683953220299',
//     projectId: 'hockey-game-80aae',
//     authDomain: 'hockey-game-80aae.firebaseapp.com',
//     storageBucket: 'hockey-game-80aae.appspot.com',
//     measurementId: 'G-D5VREM1RCZ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBCq1R7Rj6eAHsZQYx9E6G0XOOm5HHkpv4',
//     appId: '1:683953220299:android:3e66e6d2450fdddc8d894e',
//     messagingSenderId: '683953220299',
//     projectId: 'hockey-game-80aae',
//     storageBucket: 'hockey-game-80aae.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBWZSXlBAmTS3jLeKkPUko2fTt5Qc7CbF0',
//     appId: '1:683953220299:ios:0fbfcd72ad31ecba8d894e',
//     messagingSenderId: '683953220299',
//     projectId: 'hockey-game-80aae',
//     storageBucket: 'hockey-game-80aae.appspot.com',
//     iosBundleId: 'com.example.teamGiantHockey',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBWZSXlBAmTS3jLeKkPUko2fTt5Qc7CbF0',
//     appId: '1:683953220299:ios:2e731d05bb09e9168d894e',
//     messagingSenderId: '683953220299',
//     projectId: 'hockey-game-80aae',
//     storageBucket: 'hockey-game-80aae.appspot.com',
//     iosBundleId: 'com.example.teamGiantHockey.RunnerTests',
//   );
// }
